-- ----   Table for Organization  ----


-- CREATE TABLE organizations (
--   id CHAR(36) PRIMARY KEY,
--   name VARCHAR(255) NOT NULL,
--   email VARCHAR(255) NOT NULL UNIQUE,
--   userLimit INT NOT NULL,
--   imageUrl VARCHAR(255),
--   isDeactivated VARCHAR(20) DEFAULT 'No',
-- );


-- ----   Table for permission_roles  ----

-- CREATE TABLE permission_roles (
--   id CHAR(36) PRIMARY KEY,
--   name VARCHAR(255),
--   showTasksDetailPermission BOOLEAN DEFAULT FALSE,
--   projectEditPermission BOOLEAN DEFAULT FALSE,
--   showProjectPermission BOOLEAN DEFAULT FALSE,
--   userAllowanceCreatePermission BOOLEAN DEFAULT FALSE,
--   projectDeletePermission BOOLEAN DEFAULT FALSE,
--   createExpensePermission BOOLEAN DEFAULT FALSE,
--   showExpensePermission BOOLEAN DEFAULT FALSE,
--   addTaskPermission BOOLEAN DEFAULT FALSE,
--   halfDayPermission BOOLEAN DEFAULT FALSE,
--   projectCreatePermission BOOLEAN DEFAULT FALSE,
--   deleteTaskPermission BOOLEAN DEFAULT FALSE,
--   editTaskPermission BOOLEAN DEFAULT FALSE,
--   showAllProjectPermission BOOLEAN DEFAULT FALSE,
--   userAllowCrtPermission BOOLEAN DEFAULT FALSE,
--   leadPermission BOOLEAN DEFAULT FALSE,
--   offerLetterPermission BOOLEAN DEFAULT FALSE,
--   RelievingLetterPermission BOOLEAN DEFAULT FALSE,
--   ExperienceLetterPermission BOOLEAN DEFAULT FALSE,
--   leadEditPermission BOOLEAN DEFAULT FALSE,
--   leadDeletePermission BOOLEAN DEFAULT FALSE,
--   leadCreatePermission BOOLEAN DEFAULT FALSE,
--   hrManagement BOOLEAN DEFAULT FALSE,
--   permissionPagePermission BOOLEAN DEFAULT FALSE,
--   hrAdminSetupPermission BOOLEAN DEFAULT FALSE,
--   trainingSetupPermission BOOLEAN DEFAULT FALSE,
--   hrmsSetUpPermission BOOLEAN DEFAULT FALSE,
--   leadSystemPermission BOOLEAN DEFAULT FALSE,
--   attendencePermission BOOLEAN DEFAULT FALSE,
--   assetsPermission BOOLEAN DEFAULT FALSE,
--   documentPermission BOOLEAN DEFAULT FALSE,
--   leaveManagePermission BOOLEAN DEFAULT FALSE,
--   performancePermission BOOLEAN DEFAULT FALSE,
--   employeeManagePermission BOOLEAN DEFAULT FALSE,
--   payrollPermission BOOLEAN DEFAULT FALSE,
--   activeEmployeePermission BOOLEAN DEFAULT FALSE,
--   leaveRequestPermission BOOLEAN DEFAULT FALSE,
--   employeeOnLeavePermission BOOLEAN DEFAULT FALSE,
--   totalEmployeePermission BOOLEAN DEFAULT FALSE,
--   hrmsSetupEditPermission BOOLEAN DEFAULT FALSE,
--   hrmsSetupDeletePermission BOOLEAN DEFAULT FALSE,
--   hrmsSetupCreatePermission BOOLEAN DEFAULT FALSE,
--   paySlipActionPermission BOOLEAN DEFAULT FALSE,
--   leadSystemSettingEditPermission BOOLEAN DEFAULT FALSE,
--   leadSystemSettingDeletePermission BOOLEAN DEFAULT FALSE,
--   leadSystemSettingCreatePermission BOOLEAN DEFAULT FALSE,
--   leaveReqestEditPermission BOOLEAN DEFAULT FALSE,
--   leaveReqestActionPermission BOOLEAN DEFAULT FALSE,
--   employeeManageEditPermission BOOLEAN DEFAULT FALSE,
--   employeeManageActivatePermission BOOLEAN DEFAULT FALSE,
--   holidaylistPermission BOOLEAN DEFAULT FALSE,
--   organizationId CHAR(36),
--   createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
--   updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   FOREIGN KEY (organizationId) REFERENCES organizations(id)

-- );


-- ----   Table for users  ----
-- CREATE TABLE users (
--   id CHAR(36) PRIMARY KEY,
--   fullName VARCHAR(255),
--   netSalary VARCHAR(255) DEFAULT '00',
--   updateProfile BOOLEAN DEFAULT TRUE,
--   userAllowance VARCHAR(255) DEFAULT '15',
--   dob VARCHAR(255),
--   EmployeeType VARCHAR(255),
--   mobile VARCHAR(255),
--   email VARCHAR(255) UNIQUE,
--   permissionRoleId CHAR(36),
--   profileImage VARCHAR(255),
--   lastOrganization VARCHAR(255),
--   joiningDate VARCHAR(255),
--   salary VARCHAR(255),
--   bankDetails VARCHAR(255),
--   address VARCHAR(255),
--   password VARCHAR(255),
--   remainingLeaves VARCHAR(255),
--   totalLeaves VARCHAR(255),
--   role VARCHAR(50) DEFAULT 'USER',
--   isBreakIn BOOLEAN DEFAULT FALSE,
--   status VARCHAR(50) DEFAULT 'OFFLINE',
--   designation VARCHAR(255) DEFAULT 'Graphic Designer',
--   employeeCode VARCHAR(255),
--   isDeactivated VARCHAR(20) DEFAULT 'No',
--   department VARCHAR(255),
--   gmail VARCHAR(255),
--   reportingManager VARCHAR(255),
--   email1 VARCHAR(255),
--   gender VARCHAR(50),
--   createdBy VARCHAR(50) DEFAULT 'ADMIN',
--   pan VARCHAR(50),
--   adhar VARCHAR(50),
--   father VARCHAR(255),
--   currentAddress VARCHAR(255),
--   currentState VARCHAR(255),
--   currentCity VARCHAR(255),
--   currentPin VARCHAR(10),
--   residence VARCHAR(255),
--   perState VARCHAR(255),
--   perCity VARCHAR(255),
--   perPin VARCHAR(10),
--   Martial VARCHAR(50),
--   nationality VARCHAR(100),
--   Mother VARCHAR(255),
--   qualification VARCHAR(255),
--   specialization VARCHAR(255),
--   qualificationType VARCHAR(255),
--   yearPass VARCHAR(10),
--   university VARCHAR(255),
--   college VARCHAR(255),
--   percentage VARCHAR(10),
--   previousCompany VARCHAR(255),
--   previousDesignation VARCHAR(255),
--   toDate VARCHAR(20),
--   fromDate VARCHAR(20),
--   numberOfMonth VARCHAR(10),
--   Jobdescription VARCHAR(255),
--   leaveNumber VARCHAR(10),
--   SalaryPay VARCHAR(50),
--   SalaryBankName VARCHAR(255),
--   BeneficiaryName VARCHAR(255),
--   BankIfsc VARCHAR(20),
--   AccountNumber VARCHAR(50),
--   confirmAccount VARCHAR(50),
--   Branch VARCHAR(255),
--   paySlipType VARCHAR(50) DEFAULT 'Monthly Payslip',
--   enable2fa BOOLEAN DEFAULT FALSE,
--   secrets2fa VARCHAR(255),
--   organizationId CHAR(36),
--   FOREIGN KEY (organizationId) REFERENCES organizations(id),
--   FOREIGN KEY (permissionRoleId) REFERENCES permission_roles(id)
-- );


-- -- 
-- CREATE TABLE documents (
--   id CHAR(36) PRIMARY KEY,
--   name VARCHAR(255) NOT NULL,
--   url VARCHAR(255) NOT NULL,
--   userId CHAR(36),
--   FOREIGN KEY (userId) REFERENCES users(id)
-- );

-- CREATE TABLE assets (
--   id CHAR(36) PRIMARY KEY,
--   employee VARCHAR(255),
--   designation VARCHAR(255),
--   department VARCHAR(255),
--   product VARCHAR(255),
--   purchaseDate VARCHAR(20),
--   additonal VARCHAR(255),
--   description VARCHAR(255),
--   status VARCHAR(50) DEFAULT 'Pending',
--   userId CHAR(36),
--   organizationId CHAR(36),
--   FOREIGN KEY (userId) REFERENCES users(id),
--   FOREIGN KEY (organizationId) REFERENCES organizations(id)
-- );




CREATE TABLE organizations (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  userLimit INT NOT NULL DEFAULT 10,
  imageUrl VARCHAR(255),
  isDeactivated VARCHAR(20) DEFAULT 'No',

  -- subscription related fields
  subscriptionStatus ENUM('FREE', 'ACTIVE', 'EXPIRED') DEFAULT 'FREE',
  subscriptionStart DATE DEFAULT (CURRENT_DATE),
  subscriptionEnd DATE DEFAULT (DATE_ADD(CURRENT_DATE, INTERVAL 3 MONTH)),

  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE permission_roles (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255),
  showTasksDetailPermission BOOLEAN DEFAULT FALSE,
  projectEditPermission BOOLEAN DEFAULT FALSE,
  showProjectPermission BOOLEAN DEFAULT FALSE,
  userAllowanceCreatePermission BOOLEAN DEFAULT FALSE,
  projectDeletePermission BOOLEAN DEFAULT FALSE,
  createExpensePermission BOOLEAN DEFAULT FALSE,
  showExpensePermission BOOLEAN DEFAULT FALSE,
  addTaskPermission BOOLEAN DEFAULT FALSE,
  halfDayPermission BOOLEAN DEFAULT FALSE,
  projectCreatePermission BOOLEAN DEFAULT FALSE,
  deleteTaskPermission BOOLEAN DEFAULT FALSE,
  editTaskPermission BOOLEAN DEFAULT FALSE,
  showAllProjectPermission BOOLEAN DEFAULT FALSE,
  userAllowCrtPermission BOOLEAN DEFAULT FALSE,
  leadPermission BOOLEAN DEFAULT FALSE,
  offerLetterPermission BOOLEAN DEFAULT FALSE,
  RelievingLetterPermission BOOLEAN DEFAULT FALSE,
  ExperienceLetterPermission BOOLEAN DEFAULT FALSE,
  leadEditPermission BOOLEAN DEFAULT FALSE,
  leadDeletePermission BOOLEAN DEFAULT FALSE,
  leadCreatePermission BOOLEAN DEFAULT FALSE,
  hrManagement BOOLEAN DEFAULT FALSE,
  permissionPagePermission BOOLEAN DEFAULT FALSE,
  hrAdminSetupPermission BOOLEAN DEFAULT FALSE,
  trainingSetupPermission BOOLEAN DEFAULT FALSE,
  hrmsSetUpPermission BOOLEAN DEFAULT FALSE,
  leadSystemPermission BOOLEAN DEFAULT FALSE,
  attendencePermission BOOLEAN DEFAULT FALSE,
  assetsPermission BOOLEAN DEFAULT FALSE,
  documentPermission BOOLEAN DEFAULT FALSE,
  leaveManagePermission BOOLEAN DEFAULT FALSE,
  performancePermission BOOLEAN DEFAULT FALSE,
  employeeManagePermission BOOLEAN DEFAULT FALSE,
  payrollPermission BOOLEAN DEFAULT FALSE,
  activeEmployeePermission BOOLEAN DEFAULT FALSE,
  leaveRequestPermission BOOLEAN DEFAULT FALSE,
  employeeOnLeavePermission BOOLEAN DEFAULT FALSE,
  totalEmployeePermission BOOLEAN DEFAULT FALSE,
  hrmsSetupEditPermission BOOLEAN DEFAULT FALSE,
  hrmsSetupDeletePermission BOOLEAN DEFAULT FALSE,
  hrmsSetupCreatePermission BOOLEAN DEFAULT FALSE,
  paySlipActionPermission BOOLEAN DEFAULT FALSE,
  leadSystemSettingEditPermission BOOLEAN DEFAULT FALSE,
  leadSystemSettingDeletePermission BOOLEAN DEFAULT FALSE,
  leadSystemSettingCreatePermission BOOLEAN DEFAULT FALSE,
  leaveReqestEditPermission BOOLEAN DEFAULT FALSE,
  leaveReqestActionPermission BOOLEAN DEFAULT FALSE,
  employeeManageEditPermission BOOLEAN DEFAULT FALSE,
  employeeManageActivatePermission BOOLEAN DEFAULT FALSE,
  holidaylistPermission BOOLEAN DEFAULT FALSE,
  organizationId CHAR(36),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (organizationId) REFERENCES organizations(id)
);

CREATE TABLE users (
  id CHAR(36) PRIMARY KEY,
  fullName VARCHAR(255),
  netSalary VARCHAR(255) DEFAULT '00',
  updateProfile BOOLEAN DEFAULT TRUE,
  userAllowance VARCHAR(255) DEFAULT '15',
  dob VARCHAR(255),
  EmployeeType VARCHAR(255),
  mobile VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  permissionRoleId CHAR(36),
  profileImage VARCHAR(255),
  lastOrganization VARCHAR(255),
  joiningDate VARCHAR(255),
  salary VARCHAR(255),
  bankDetails VARCHAR(255),
  address VARCHAR(255),
  password VARCHAR(255),
  remainingLeaves VARCHAR(255),
  totalLeaves VARCHAR(255),
  role VARCHAR(50) DEFAULT 'USER',
  isBreakIn BOOLEAN DEFAULT FALSE,
  status VARCHAR(50) DEFAULT 'OFFLINE',
  designation VARCHAR(255) DEFAULT 'Graphic Designer',
  employeeCode VARCHAR(255),
  isDeactivated VARCHAR(20) DEFAULT 'No',
  department VARCHAR(255),
  gmail VARCHAR(255),
  reportingManager VARCHAR(255),
  email1 VARCHAR(255),
  gender VARCHAR(50),
  createdBy VARCHAR(50) DEFAULT 'ADMIN',
  pan VARCHAR(50),
  adhar VARCHAR(50),
  father VARCHAR(255),
  currentAddress VARCHAR(255),
  currentState VARCHAR(255),
  currentCity VARCHAR(255),
  currentPin VARCHAR(10),
  residence VARCHAR(255),
  perState VARCHAR(255),
  perCity VARCHAR(255),
  perPin VARCHAR(10),
  Martial VARCHAR(50),
  nationality VARCHAR(100),
  Mother VARCHAR(255),
  qualification VARCHAR(255),
  specialization VARCHAR(255),
  qualificationType VARCHAR(255),
  yearPass VARCHAR(10),
  university VARCHAR(255),
  college VARCHAR(255),
  percentage VARCHAR(10),
  previousCompany VARCHAR(255),
  previousDesignation VARCHAR(255),
  toDate VARCHAR(20),
  fromDate VARCHAR(20),
  numberOfMonth VARCHAR(10),
  Jobdescription VARCHAR(255),
  leaveNumber VARCHAR(10),
  SalaryPay VARCHAR(50),
  SalaryBankName VARCHAR(255),
  BeneficiaryName VARCHAR(255),
  BankIfsc VARCHAR(20),
  AccountNumber VARCHAR(50),
  confirmAccount VARCHAR(50),
  Branch VARCHAR(255),
  paySlipType VARCHAR(50) DEFAULT 'Monthly Payslip',
  enable2fa BOOLEAN DEFAULT FALSE,
  secrets2fa VARCHAR(255),
  organizationId CHAR(36),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  FOREIGN KEY (organizationId) REFERENCES organizations(id) ON DELETE CASCADE,
  FOREIGN KEY (permissionRoleId) REFERENCES permission_roles(id) ON DELETE SET NULL
);

CREATE TABLE documents (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  userId CHAR(36),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE assets (
  id CHAR(36) PRIMARY KEY,
  employee VARCHAR(255),
  designation VARCHAR(255),
  department VARCHAR(255),
  product VARCHAR(255),
  purchaseDate VARCHAR(20),
  additonal VARCHAR(255),
  description VARCHAR(255),
  status VARCHAR(50) DEFAULT 'Pending',
  userId CHAR(36),
  organizationId CHAR(36),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (organizationId) REFERENCES organizations(id)
);

-- CREATE TABLE organizations (
--   id CHAR(36) PRIMARY KEY,
--   name VARCHAR(255) NOT NULL,
--   email VARCHAR(255) NOT NULL UNIQUE,
--   imageUrl VARCHAR(255),
--   isDeactivated VARCHAR(20) DEFAULT 'No',
--   default_currency VARCHAR(10) DEFAULT 'INR',
--   country VARCHAR(100),
--   state VARCHAR(100),
--   city VARCHAR(100),
--   address_line1 VARCHAR(255),
--   address_line2 VARCHAR(255),
--   zip_code VARCHAR(20),  
--   phone VARCHAR(20),
--   website VARCHAR(255),
--   gstin VARCHAR(20),
--   pan VARCHAR(20),
--   tan VARCHAR(20),
--   tin VARCHAR(50),
--   lst VARCHAR(50),
--   cst VARCHAR(50),
--   fssai_no VARCHAR(50),
--   service_tax_no VARCHAR(50),
--   tax_inclusive BOOLEAN DEFAULT FALSE,
--   transfer_type VARCHAR(50),
--   bank_name VARCHAR(100),
--   branch_name VARCHAR(100),
--   account_number VARCHAR(50),
--   ifsc_code VARCHAR(20),
--   swift_code VARCHAR(20),
--   upi_id VARCHAR(50),
--   account_holder_name VARCHAR(100),
--   contact_person_name VARCHAR(255)
-- );



CREATE TABLE IF NOT EXISTS asset (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_name VARCHAR(150) NOT NULL,         
    identification_number VARCHAR(100) UNIQUE,
    asset_condition VARCHAR(50),         
    model_number VARCHAR(100),               
    attachment VARCHAR(255),                   
    current_value DECIMAL(12,2) DEFAULT 0.00, 
    acquired_date DATE,                       
    comments TEXT, 
    organizationId CHAR(36),                          
    is_allocated TINYINT(1) DEFAULT 0,  
    allocated_to CHAR(36),                
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_asset_org FOREIGN KEY (organizationId) REFERENCES organizations(id),
    CONSTRAINT fk_asset_user FOREIGN KEY (allocated_to) REFERENCES users(id)
);


CREATE TABLE IF NOT EXISTS asset_transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    employee_id CHAR(36),       
    asset_id INT NOT NULL,          
    allocate_date DATE NOT NULL,   
    comments TEXT,                 
    notify_email BOOLEAN DEFAULT FALSE,

    -- deallocation fields
    deallocation_date DATE DEFAULT NULL,
    handed_over_to CHAR(36) DEFAULT NULL,
    return_condition ENUM('Good', 'Average', 'Bad') DEFAULT NULL,
    deallocation_description TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    organizationId CHAR(36),

    CONSTRAINT fk_asset_txn_employee FOREIGN KEY (employee_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_asset_txn_asset FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE CASCADE,
    CONSTRAINT fk_asset_txn_handover FOREIGN KEY (handed_over_to) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_asset_txn_org FOREIGN KEY (organizationId) REFERENCES organizations(id)
);

